# Generated by Django 4.1 on 2024-12-01 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuoWrapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('term_selection', models.CharField(max_length=20)),
                ('favorite_artists', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_tracks', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_genres', models.JSONField(blank=True, default=list, null=True)),
                ('quirkiest_artists', models.JSONField(blank=True, default=list, null=True)),
                ('llama_description', models.TextField(blank=True, null=True)),
                ('llama_songrecs', models.TextField(blank=True, null=True)),
                ('datetime_created', models.CharField(default='2024-11-30-17-31-20-637065', max_length=50)),
                ('user2', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('runTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyWrapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('term_selection', models.CharField(max_length=20)),
                ('favorite_artists', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_tracks', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_genres', models.JSONField(blank=True, default=list, null=True)),
                ('quirkiest_artists', models.JSONField(blank=True, default=list, null=True)),
                ('llama_description', models.TextField(blank=True, null=True)),
                ('llama_songrecs', models.TextField(blank=True, null=True)),
                ('datetime_created', models.CharField(default='2024-11-30-17-31-20-637065', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('favorite_tracks_short', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_tracks_medium', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_tracks_long', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_artists_short', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_artists_medium', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_artists_long', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_genres_short', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_genres_medium', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_genres_long', models.JSONField(blank=True, default=list, null=True)),
                ('quirkiest_artists_short', models.JSONField(blank=True, default=list, null=True)),
                ('quirkiest_artists_medium', models.JSONField(blank=True, default=list, null=True)),
                ('quirkiest_artists_long', models.JSONField(blank=True, default=list, null=True)),
                ('past_roasts', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
