# Generated by Django 4.1 on 2024-12-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duowrapped',
            name='datetime_created',
            field=models.CharField(default='2024-11-30-17-31-45-053222', max_length=50),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='datetime_created',
            field=models.CharField(default='2024-11-30-17-31-45-053222', max_length=50),
        ),
    ]
