# Generated by Django 4.1 on 2024-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0002_spotifyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='llama_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
