# Generated by Django 4.1 on 2024-11-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0005_alter_spotifyuser_favorite_artists_long_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyWrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_selection', models.CharField(max_length=20)),
                ('favorite_artists', models.JSONField(blank=True, default=dict, null=True)),
                ('favorite_tracks', models.JSONField(blank=True, default=dict, null=True)),
                ('favorite_genres', models.JSONField(blank=True, default=list, null=True)),
                ('quirkiest_artists', models.JSONField(blank=True, default=dict, null=True)),
                ('llama_description', models.TextField(blank=True, null=True)),
                ('llama_songrecs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spotifyuser',
            name='llama_description',
        ),
        migrations.RemoveField(
            model_name='spotifyuser',
            name='llama_songrecs',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='past_roasts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='display_name',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_genres_long',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_genres_medium',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_genres_short',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='DuoWrapped',
            fields=[
                ('spotifywrapped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spotify_data.spotifywrapped')),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
            bases=('spotify_data.spotifywrapped',),
        ),
    ]
