# Generated by Django 4.1 on 2024-11-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0007_alter_duowrapped_unique_together_spotifywrapped_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_artists_long',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_artists_medium',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_artists_short',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_tracks_long',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_tracks_medium',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='favorite_tracks_short',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='quirkiest_artists_long',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='quirkiest_artists_medium',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='quirkiest_artists_short',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='favorite_artists',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='favorite_tracks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='quirkiest_artists',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
