# Generated by Django 4.1 on 2024-11-29 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0008_alter_spotifyuser_favorite_artists_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrapped',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
