# Generated by Django 4.1 on 2024-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0009_spotifywrapped_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifywrapped',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
