# Generated by Django 4.1 on 2024-11-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0010_alter_spotifywrapped_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifywrapped',
            name='datetime_created',
            field=models.CharField(default='2024-11-29-23-10-03-880839', max_length=50),
        ),
    ]
