# Generated by Django 4.1 on 2024-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0011_alter_spotifywrapped_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifywrapped',
            name='datetime_created',
            field=models.CharField(default='2024-11-30-14-58-15-612697', max_length=50),
        ),
    ]
