# Generated by Django 4.1 on 2024-11-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='username',
            field=models.CharField(default='default', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
